name: stok_takip
description: Bu bir YuTech 端r端n端d端r.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  adaptivex: ^0.0.1+5
  another_flushbar: ^1.12.29
  auto_route: ^6.1.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.8
  dio: ^4.0.6
  phone_form_field: ^7.1.0
  dropdown_search: ^5.0.3
  email_validator: ^2.0.1
  envied: ^0.2.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_profile_picture: ^2.0.0
  flutter_secure_storage: ^8.0.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.1.0
  function_tree: ^0.8.13
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  http_interceptor: ^1.0.2
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  pretty_qr_code: ^2.0.3
  shared_preferences: ^2.0.15
  supabase_flutter: ^1.6.2
  turkish: ^0.2.1
  url_strategy: ^0.2.0
  xml: ^6.1.0
  xml2json: ^5.3.5
  quantity_input: ^1.0.2
  input_quantity: ^1.1.3
  multiple_stream_builder: ^3.0.2
  printing: ^5.9.3
  pie_chart: ^5.3.2
  flutter_speed_dial: ^6.2.0
  flutter_textfield_autocomplete: ^1.0.2  
  synchronized: ^3.0.1
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.3.0
  group_radio_button: ^1.3.0
  searchfield: ^0.7.5
  
  
  
 
  
  

 
  

dev_dependencies:
  auto_route_generator: ^6.1.0
  build_runner: 
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo_transparent.png
    - assets/gider.png
   
    
